// <auto-generated />
using System;
using CampusVirtualWeb.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusVirtualWeb.Migrations
{
    [DbContext(typeof(AsignaturaContext))]
    [Migration("20240626173701_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CampusVirtualWeb.Models.Asignaturas", b =>
                {
                    b.Property<Guid>("AsignaturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Horario")
                        .HasColumnType("int");

                    b.Property<string>("Nivelacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreAsignatura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AsignaturaId");

                    b.ToTable("Asignatura", (string)null);
                });

            modelBuilder.Entity("CampusVirtualWeb.Models.Matriculas", b =>
                {
                    b.Property<Guid>("MatriculaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AsignaturaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreAsignatura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PrioridadMatricula")
                        .HasColumnType("int");

                    b.Property<string>("Profesor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Semestreinscripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoInscripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MatriculaId");

                    b.HasIndex("AsignaturaId");

                    b.ToTable("Matricula", (string)null);
                });

            modelBuilder.Entity("CampusVirtualWeb.Models.Matriculas", b =>
                {
                    b.HasOne("CampusVirtualWeb.Models.Asignaturas", "AsignaturasVirtual")
                        .WithMany("MatriculaVirtual")
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsignaturasVirtual");
                });

            modelBuilder.Entity("CampusVirtualWeb.Models.Asignaturas", b =>
                {
                    b.Navigation("MatriculaVirtual");
                });
#pragma warning restore 612, 618
        }
    }
}
