// <auto-generated />
using System;
using CampusVirtualWeb.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusVirtualWeb.Migrations
{
    [DbContext(typeof(AsignaturaContext))]
    [Migration("20240627204929_DataInicial")]
    partial class DataInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CampusVirtualWeb.Models.Asignaturas", b =>
                {
                    b.Property<Guid>("AsignaturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Horario")
                        .HasColumnType("int");

                    b.Property<string>("Nivelacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreAsignatura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfesorAsignatura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AsignaturaId");

                    b.ToTable("Asignatura", (string)null);

                    b.HasData(
                        new
                        {
                            AsignaturaId = new Guid("d97c9709-1b2e-4084-aee3-17094f61bf74"),
                            FechaRegistro = new DateTime(2024, 6, 27, 15, 49, 28, 950, DateTimeKind.Local).AddTicks(2847),
                            Horario = 4,
                            Nivelacion = "No",
                            NombreAsignatura = "Calculo",
                            ProfesorAsignatura = "Pedro Diaz"
                        },
                        new
                        {
                            AsignaturaId = new Guid("d97c9709-1b2e-4084-aee3-17094f61bf02"),
                            FechaRegistro = new DateTime(2024, 6, 27, 15, 49, 28, 950, DateTimeKind.Local).AddTicks(2895),
                            Horario = 2,
                            Nivelacion = "No",
                            NombreAsignatura = "Ingles",
                            ProfesorAsignatura = "Luisa Fernandez"
                        });
                });

            modelBuilder.Entity("CampusVirtualWeb.Models.Matriculas", b =>
                {
                    b.Property<Guid>("MatriculaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AsignaturaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreAsignatura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PrioridadMatricula")
                        .HasColumnType("int");

                    b.Property<string>("Profesor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Semestreinscripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoInscripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MatriculaId");

                    b.HasIndex("AsignaturaId");

                    b.ToTable("Matricula", (string)null);

                    b.HasData(
                        new
                        {
                            MatriculaId = new Guid("d97c9709-1b2e-4084-aee3-17094f61bf03"),
                            AsignaturaId = new Guid("d97c9709-1b2e-4084-aee3-17094f61bf74"),
                            FechaRegistro = new DateTime(2024, 6, 27, 15, 49, 28, 951, DateTimeKind.Local).AddTicks(5448),
                            NombreAsignatura = "Calculo",
                            PrioridadMatricula = 1,
                            Profesor = "Pedro Diaz",
                            Semestreinscripcion = "Primero",
                            TipoInscripcion = "Virtual"
                        },
                        new
                        {
                            MatriculaId = new Guid("d97c9709-1b2e-4084-aee3-17094f61bf04"),
                            AsignaturaId = new Guid("d97c9709-1b2e-4084-aee3-17094f61bf02"),
                            FechaRegistro = new DateTime(2024, 6, 27, 15, 49, 28, 951, DateTimeKind.Local).AddTicks(5480),
                            NombreAsignatura = "Ingles",
                            PrioridadMatricula = 1,
                            Profesor = "Luisa Fernandez",
                            Semestreinscripcion = "Primero",
                            TipoInscripcion = "Virtual"
                        });
                });

            modelBuilder.Entity("CampusVirtualWeb.Models.Matriculas", b =>
                {
                    b.HasOne("CampusVirtualWeb.Models.Asignaturas", "AsignaturasVirtual")
                        .WithMany("MatriculaVirtual")
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsignaturasVirtual");
                });

            modelBuilder.Entity("CampusVirtualWeb.Models.Asignaturas", b =>
                {
                    b.Navigation("MatriculaVirtual");
                });
#pragma warning restore 612, 618
        }
    }
}
